# AdGuard Home configuration
dns:
  rewrites:
    - domain: adguard.lab.local
      answer: 192.168.68.10
    - domain: ollama.lab.local
      answer: 192.168.68.10
    - domain: forgejo.lab.local
      answer: 192.168.68.10
    - domain: auth.lab.local
      answer: 192.168.68.10
    - domain: headlamp.lab.local
      answer: 192.168.68.10
schema_version: 27
