apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: ai
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:bRWoCQKxavR2yKuvHYkohl6opOd8hTKgPXxqIvmZHmcqIcRqr4fR,iv:Np3FRVLe6hJFFtib3VYKgxfcOFpStWqXYYkDpoHzxkA=,tag:c2G4EXyHiAFc0KYQUX1q0Q==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:dekuSPikZRbCdZoT+BjcdYUT2PgODeBhmg0tWAS1woi5Tk++8ATjRzbzvQ744A==,iv:tAljA+IHfMNsCkBL58nDSO3rThvNx+fBoi2DQobbqS4=,tag:5lys7uEecGfwOjkdpYk8/w==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:QqT5JyUXD06gpQ==,iv:IKzUATJLXYQRDgFPc9pAt0e8WyjdAtBbrT0ltZAtNmo=,tag:kVBsZu0ykeKUoCAxeAZ/WQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydmp1dlRYbThoN2JpcjRs
            enZSUnlkZDBuSDRtN015U2xaaklVVHhtWkdVClpsTHZEcGxleUJadklFaWxWdm54
            aTF5c0I2Si95VVFRNGhQMnpCQXhDeGMKLS0tIFdwTGFIR2Y2Sm9Rd29KK28vR1JU
            OG1vc09kWGdGdmdCZXY5TEswSXdnVGMKwou1aiDSuyRNotna0qbTvpklgHDUU9pH
            m/lfjinmoMqgPlGClJ4fJUfJRdleMpUjEO/TTSxDHEV/NWLctG8TFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T07:41:15Z"
    mac: ENC[AES256_GCM,data:4uoM27bJCRPlNRhmy8d0Z20MuGoW6cDS40IaogXmiz2UVCNa9uEG6v8nv/lFjLFPUSpdY1GPuWrp0dxT922sbErZwE6KntE2vMDsEvnGMDmfCs6Ijqy+SRCBwpZZ8kNjPBh/Vzo9luVVBjjtKp6xCRdRaZllONXeUiTqKj9RwWk=,iv:QkI30Uq5/qCbDuSpKzQbTCO4GOLdOBJR1+Oo25V2kis=,tag:R8sy/Y5jb/YzzjoqsE6p5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
