apiVersion: ENC[AES256_GCM,data:we0=,iv:GqmCwU3pYF248hb3s3eKlt5M6rTa2g/S7xuB3t3VjJ4=,tag:DM172+QnPgqwlFNIxH7VYg==,type:str]
kind: ENC[AES256_GCM,data:8ts9MGKW,iv:9YtTxxmgVVKepEmNLmPzbfRMFzSFgj5liC1X5B3DhJI=,tag:5MWdGzm2DEGyj7jdfUf+Wg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5hFrYj1JqDIZ60N3jII=,iv:kC1emep7xdVTxdsoxtUcWrySNF6gqgOssIlblRq8OmY=,tag:7+V8dDkzpORJlUfRtTs2gw==,type:str]
    namespace: ENC[AES256_GCM,data:4VM=,iv:Bp6/RF/+SgGC91C/D6pFQAw+gh+ibWgzFPnW1iyweyc=,tag:2sVl40VeBnTTUpxPTl2Ncg==,type:str]
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:HRJ+3EMvg1hBUlGj1Wt3u+494ZBG2MTrSLjURzNlARh8RNiFzvU4,iv:rfMEMXDdFxvn9PWXjazBYuHof7fbZIti1/WopA5Wm3E=,tag:JO51w8P4y1SktVAKkQt3sQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:9Cg4VusiM3i1hfBWvrnsPVGEBfQwhbvu4XvhF0Vy0GlnodTy0n+nTQleDWRt3w==,iv:op2/1bnq8BoJTLsSTljTlEnvzQpFYuz0eV/f3VvCNtY=,tag:AzoUo87ZxxVEp9eAcQAPsA==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:zcGPQST0EaFWqQ==,iv:/9FZZecYWWdR/e7RclMlo2IOzUYt5wVsE7S5N9C0DlY=,tag:fPoiR3AeVseO8IFZTit/bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSHh6Wm1DQUJGNG1xVExp
            T3lNSU9UMXRFRFM0eWp6emh5bGRBU3dBWG4wCmM4QTQvam13dmRPZkZWcE9VMnpG
            d3gyL3lUSy93cEx5ZEEyQTZJTmI4NHMKLS0tIE5qN0dBZVdMaVBHTUwxejRPcTBw
            bnJMaHRWdWtKcjZqd1F3Z01EdTU4S1UKvuC7aH427b7+Kz22h7ajiPs8T9lfFA1i
            Eo8CpcuqmeIbcwRc51H1WtWNhS0+7AFWuFu2xtzIYUev6q3gU2yhmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T20:59:11Z"
    mac: ENC[AES256_GCM,data:bHtgB9JEob06oqTQvSR5O2QNEeOWG4I7O8xL/3At3Z72ddEEjj4SVViJmnhH52HOnum1M8IWp3jovvB7su3KT3kzrKBq1NvvFTGIoZ3PdSBnXwxp3KM/Cl9/PHTAVeK4eHkWlGaj8yrUe5+f0Xp/m9IVMN1euRPnsLJghnz/ivY=,iv:FcGaFIbaXGi0JjpIYcrJewCGj8Pf3c+J+WqjkwgfCac=,tag:ic5wyx/uSq8HWNRat7kUqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
