apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: networking
stringData:
  # Values for JWT_SECRET, SESSION_SECRET, and STORAGE_ENCRYPTION_KEY
  # I'll set some default ones for now.
  JWT_SECRET: "my-jwt-secret-placeholder"
  SESSION_SECRET: "my-session-secret-placeholder"
  STORAGE_ENCRYPTION_KEY: "my-storage-encryption-key-placeholder"
