apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - repository-grafana.yaml
  - release.yaml
  - uptime-kuma
  - loki
  - monitors.yaml
  - traefik-monitor.yaml
