apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-cpu
  namespace: ai
spec:
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
        namespace: ai
      version: "0.68.0"
  interval: 1h
  values:
    ollama:
      models:
        - llama3.2:1b
        - smollm2:135m
    persistentVolume:
      enabled: true
      size: 10Gi
