apiVersion: ENC[AES256_GCM,data:V9M=,iv:MUAXG+53nHeGt1tLn07uLUkWlz8v92cqhuKd2i24ciQ=,tag:6B3MFAi+YB2JhmO3JQyRIQ==,type:str]
kind: ENC[AES256_GCM,data:INcbBSDT,iv:4aE+S1zzLSRko1I4nFWYQYdPqymdkrwII7ryO3Dxv/E=,tag:AOV85WE777s7gGIWB0oj1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E7VlWAHNmpKruAvn5vbi+p30zlPhbWpFSVSD,iv:JUPIOKWuU0Y1EVjV+D+/lWhMV9h4KJoWanqvdYj0om0=,tag:VVpZX2TPOsYAUzBMd+9EQQ==,type:str]
    namespace: ENC[AES256_GCM,data:f9eNOijjfw0XDXGG,iv:7FB4pqC2A+uMs8PwXXyaV2Rj2M8v+ZrYp/g3sBKVLBs=,tag:HWQ0NBk1JnB3WSfBb4YU8A==,type:str]
type: ENC[AES256_GCM,data:8f43f8Gt,iv:EiJIh1h4FjdIpaG9ORinpKdHP1Uyk3RHrsjUVC3+lXg=,tag:1XYS3W3MHoZVbFYC99ASjQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:qw9a98WBubdSZ5Hf7fNNfkOz/2PvLOKupA==,iv:Q/F80DcBCWubBNYFv0GjdMkrsQ8m/X/hPZwIUK0vnOU=,tag:6pt5+yMCom4xvED17RENAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNGFDZWh3UUlaS21MTXlp
            WkNLVFZXQm1veERYaHcrTnJEeUp4a3pkODFRCkNoZGZOelN4bVZyaWgxTE9NWUZn
            bDZZUjVSb1BlU3pzZWtpSDNwMGx3TjgKLS0tIEdoL1NUSk5ZeU5rS3BxdDJnVlB5
            R1JJYWFQYTZFTThGOE5KQWxZVk53amsKuTQnpBGe8atce38BV3fG9iHWizn1zRpv
            XbeHcVOSZMAz5OBh1F9KpIIJp5b4I9vUlUYJW/9bNyWxq9dmNWDThQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T09:26:49Z"
    mac: ENC[AES256_GCM,data:kKYLQHDGB6wR3WhQbADeM5P1xZoJ/+SFWX/w0/kOf97hjlz3nEqXHI2fZrVCLZolydU9zuDFR6l2Xf+/LPrZATLywBhLWCoaDIX9SOSqvDt+Eq1bi6cJMXJpcVHsG8ZODWcjXsfzbRFWqXJvyjHvyPv0wVLcWz3af7jJtN7amto=,iv:VsWKs6L105UW/PR3ap3BzekHtMb06tyYbnfoCA39BWw=,tag:04PAmWt+X+vm0IX1mdFVkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
