apiVersion: ENC[AES256_GCM,data:t9I=,iv:XDhnkTozIas0IJpRQszHcLxgrQVIudzm/TOw5StaT1A=,tag:CRLhXEuupRM1IFCWpMDTNg==,type:str]
kind: ENC[AES256_GCM,data:hyOPqvuO,iv:/VoDdE4dm1Fj6Vyh1mKNKK0ivje5JkJD4OgwJ1X7EP4=,tag:8SJPHJyNFrZxmFQpGf6fTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eCnS7W1Jrrj3edo7h2YTU0XTxqE7,iv:scAsiUNXLCUVlaZ+S9jHHz/R7wonIWh/GLtuPTdeLq8=,tag:90pA6hlp6Jfegl97IpZ4Bw==,type:str]
    namespace: ENC[AES256_GCM,data:0PJYfe1lZugJnt4=,iv:XE3rQofjcMpVD/UossfENXzo6rlMFYKdDX+9FEIEfPE=,tag:EbKGSe+NOqTHpzRR+iN/Ig==,type:str]
stringData:
    #ENC[AES256_GCM,data:uOq39bhaHjkDBqiWF/zfMm2RiNF1rswLxwhN6/gDaod6Oz0LEJHO8l+DPD8nKNjEaaBO/oq2Pcf9Ji6ioJ0lVwE8le/dmm/WU27f3vCVWqjqriyilzdz40fD6x5cl02/,iv:H9lLRsnjxTt9F8yiyZOOWAbkVCYShQ9qbzcUKnHKVc4=,tag:wNSE+4a4egQXsLTIBTJTSA==,type:comment]
    token: ENC[AES256_GCM,data:SItGT04M4mREV+QEY9zXo3V0qxa3j3qhryHuohWn,iv:YfWSk+uPXixgjqQQ9ap9vl3UpPhDAM3cxAXD0u/DKMo=,tag:gPOnQDU1fTxeXYoiwk5Ygw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RFRNSkIzd0tsTUZPZEFH
            alNKU1ViZjlxTEpHQjNsM29HbzFWZEtXMmcwCi9WSlNWOGFQMnVMWE9jL0J4V3U3
            SDlyNHRhUndoaHFFaVJuYTBacnpxRlEKLS0tIDR2SjkvMDVMZG9rMDY5Slk3ZW40
            RWhxUVpSWnRpTk1odU0xZnpxLzUrckkK1mFqJAEEb4CE7Lh/lyEzBiyaYcDG7jyB
            cLm0+thqSFTuuWblefxHxkefcX+g5Td/YKqK42qdVCRTBDWsruTRaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T16:59:59Z"
    mac: ENC[AES256_GCM,data:XC5lnze0Gnl1fl9PY4Awzdt8ZF+Y27Q+FR7PgmqmMhSc8bWRxPKrXbhQAKSWonJPWcZBnXNmKetrGzcRf+FcWyUtSW5IjTRkQztymF+OadHkw+OdhcqjazRo/JHlPAuTbwqAjhmsDEZ0uvxSubRe1IamCbuS6fooHn1bLMs2iR4=,iv:L/KOatsZgZ88DtqO5GtwHHpHqqoHd2Iy13A2FpCuPEo=,tag:D5RpnjGLULifLWukNgDTKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
