apiVersion: ENC[AES256_GCM,data:t9I=,iv:XDhnkTozIas0IJpRQszHcLxgrQVIudzm/TOw5StaT1A=,tag:CRLhXEuupRM1IFCWpMDTNg==,type:str]
kind: ENC[AES256_GCM,data:hyOPqvuO,iv:/VoDdE4dm1Fj6Vyh1mKNKK0ivje5JkJD4OgwJ1X7EP4=,tag:8SJPHJyNFrZxmFQpGf6fTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eCnS7W1Jrrj3edo7h2YTU0XTxqE7,iv:scAsiUNXLCUVlaZ+S9jHHz/R7wonIWh/GLtuPTdeLq8=,tag:90pA6hlp6Jfegl97IpZ4Bw==,type:str]
    namespace: ENC[AES256_GCM,data:0PJYfe1lZugJnt4=,iv:XE3rQofjcMpVD/UossfENXzo6rlMFYKdDX+9FEIEfPE=,tag:EbKGSe+NOqTHpzRR+iN/Ig==,type:str]
stringData:
    #ENC[AES256_GCM,data:uOq39bhaHjkDBqiWF/zfMm2RiNF1rswLxwhN6/gDaod6Oz0LEJHO8l+DPD8nKNjEaaBO/oq2Pcf9Ji6ioJ0lVwE8le/dmm/WU27f3vCVWqjqriyilzdz40fD6x5cl02/,iv:H9lLRsnjxTt9F8yiyZOOWAbkVCYShQ9qbzcUKnHKVc4=,tag:wNSE+4a4egQXsLTIBTJTSA==,type:comment]
    token: ENC[AES256_GCM,data:dmMOzJD25236NEYapOYXBGWNfE6+bdwf8qcvSRW/mIleqOwOpPeXxXLEfg==,iv:aeB9oqm9tn8ZeSQ+px7JVd1Y/v0OG1pVBWzslIKPw+k=,tag:LLUelKIAXaugOP5RLJJ5Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RFRNSkIzd0tsTUZPZEFH
            alNKU1ViZjlxTEpHQjNsM29HbzFWZEtXMmcwCi9WSlNWOGFQMnVMWE9jL0J4V3U3
            SDlyNHRhUndoaHFFaVJuYTBacnpxRlEKLS0tIDR2SjkvMDVMZG9rMDY5Slk3ZW40
            RWhxUVpSWnRpTk1odU0xZnpxLzUrckkK1mFqJAEEb4CE7Lh/lyEzBiyaYcDG7jyB
            cLm0+thqSFTuuWblefxHxkefcX+g5Td/YKqK42qdVCRTBDWsruTRaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T17:41:12Z"
    mac: ENC[AES256_GCM,data:5/y1C9fMOXAhTxNWlxEzaEnMZxErlvVuuMFnzdTZCYZ+FzEhr9EUkFwtIm15PaoNfjZTV5/O3c071V3Y63TIwEZmcEN2R0M6oRDv2c7jGFg0us5YJrc4qLCkTxkkcaW/E2FuFOLO2OY2+ZC7IFIwAKmziQi1wCcwUP82yfKfTyk=,iv:7DVtc2hg7uN9tUFjlaEqJG8TXJx8KRCGK499dQuWwjQ=,tag:8YN6HlZuR2cE9fyk2ox0rQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
