apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: auth
  values:
    domain: lab.local
    configMap:
      disabled: true
    secret:
      disabled: true
      existingSecret: authelia-secrets

    pod:
      env:
        - name: AUTHELIA_CONFIG_FILTERS
          value: "template"
        - name: X_AUTHELIA_CONFIG
          value: "/config/configuration.yaml"
        - name: AUTHELIA_SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia-secrets
              key: session_secret
        - name: AUTHELIA_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia-secrets
              key: jwt_secret
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: authelia-secrets
              key: storage_encryption_key
        - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia-secrets
              key: jwt_secret
    
    volumes:
      - name: authelia-config
        configMap:
          name: authelia-config
      - name: users-db
        configMap:
          name: authelia-users
    volumeMounts:
      - name: authelia-config
        mountPath: /config/configuration.yaml
        subPath: configuration.yaml
        readOnly: true
      - name: users-db
        mountPath: /config/users.yml
        subPath: users.yml
        readOnly: true

    persistence:
      enabled: true
      size: 1Gi
      storageClass: local-path
    ingress:
      enabled: false
