apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: auth
stringData:
  JWT_SECRET: "my-jwt-secret-placeholder"
  SESSION_SECRET: "my-session-secret-placeholder"
  STORAGE_ENCRYPTION_KEY: "my-storage-encryption-key-placeholder"
