apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: auth
stringData:
  jwt_secret: "my-jwt-secret-placeholder"
  session_secret: "my-session-secret-placeholder"
  storage_encryption_key: "my-storage-encryption-key-placeholder"
