apiVersion: ENC[AES256_GCM,data:Fqs=,iv:g+0MXIo/wXlCukZgbPeSbl8oOsD+MLeJLw3ogCqkW10=,tag:EJXLQpljSQXp3tssxPlZzQ==,type:str]
kind: ENC[AES256_GCM,data:jGliHTPF,iv:X+ILAiQh73CE3Lcl+e7LDEnK6s80CVub6wy94M5LRY8=,tag:abNAhc2GU8pNc32EkSDomw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LrZSpU+G0wS58GQ1sZY=,iv:S2DTU7ipWyscs2dEW4uiwznK37Cg1knZ3IJV85HQhIU=,tag:a0l89YOS8uECnAlWgmlpcg==,type:str]
    namespace: ENC[AES256_GCM,data:ZTo=,iv:J3zLrc9rApslXHDDB7Y9HqZ5XbykOIKPInkrIgwTHes=,tag:8zQ3MZ8oKQu35aIoVosG6A==,type:str]
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:Yq0xG1zDwuTlMExHdfs0GcdcbF1+/Gq84yDIKMllgGEqt8sZ7lvW,iv:h656mB18siaO1J+2G8oIH9HRnfZaJM5y2+RTKD4usnY=,tag:rxgT6bG67I66L8ag+C9QZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU3p2Z1ZxU3A4b2xmQy92
            YXF5TjkrZ3NhRnRpMFlvUy9KdnFCYmJ4cjB3CnR1MW5wb09Xamx5d0dqalNUQnJ3
            MmlPUWlMcklhT09JeElWODJ5TGVUbzQKLS0tIFp5S2dKWitKakxmNG9CNXhEWlM2
            NTZIZ1NoazlsVjBWZ2xoZUlIOC82Z2sKn/Fh+73hlW16I+m2SZrM/XLlPq7j+tnV
            PkOyX5cmkIJqEtzIo3ZAMSdG7ihiD5FEm454TYQrlh2bosIXbUJj6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:49:27Z"
    mac: ENC[AES256_GCM,data:hVBu3Fe95LvkEOzQzqCObwh13jXMlQ/zXGXTa4y72vc7rtbpsCR+bLovzP5ndNDYPOd5ezg9aFyIh2qZ44UHW2VH38R3GuNBjPBF2NWhd1BvYIH8QIBqbuXpafEQiOUtTIvOVfifdI6g2z8DxPhHimYjTKqhiepEcTggtb797t4=,iv:oqHHrk8NwTS90FF1Hx5UJyqZqm8/oeLU0yPK/2REcHg=,tag:VOqy4S3861b6NRhoJjXjOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
