apiVersion: ENC[AES256_GCM,data:PjE=,iv:TBl8dC2GaWIJ19WX7VorTFOvjp599qG+2EPTmqpe/5M=,tag:2g/A6kHCsn/fknmsXrFqtw==,type:str]
data:
    cloud: ENC[AES256_GCM,data:uA3T29Kt1fNXwzexscxgF0+zwxC7xo1HhXlGvBDPha0bbsNl2EElM7sMVVNIVr0URSpwftq9AzdGfxW+0bM+ew8miCUXO1X/lYpcMB5Et4UAqfeHXowrJmu9wps2U/p+WnL+8dHFaxzM1SCcgb9xAfFhSPduTmuw9AtAOo2n498tb5+ZNdRAk98BxMbznuR3qQp20fTAg6eJUdyvVr2xgWvoqUNki68H7VpICPicYiXXWUvFjiPtSsIBpCrfyHWzge9JqLXcvR45Dl3r,iv:zt+LDphrP6agQ1J6QdtHmY3GyPuAvZ06wevu7n3FVdQ=,tag:qc2FDVvJiouNZ1JoqqJCmg==,type:str]
kind: ENC[AES256_GCM,data:WETf2Drl,iv:aFDMXNNoT5EpqC6EJCMZioUfGXGP6fWtT2dFtMk2T/Q=,tag:1hQ/Vu5kwdCL/E52DyeRyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:b5wn6q+iYaG22n3OvBK5yRiN6sYf,iv:eQdzregpGuNPimV81fq9XsWHl5evauinsLikQNDhKTc=,tag:hgcmQ2HYZ+qndyPYgbCcTQ==,type:str]
    namespace: ENC[AES256_GCM,data:xrhqvmgiqfZcvds=,iv:kvlZpMJPaYTzWF0Ckpl8hqOvaOhOeKDCF/TEJGQAplA=,tag:Q7Is3fqSCL+K3V0QzShUyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd0haSjZ2SDBKZWVGdGFj
            aGllWXRWUGxVRnNxLzl5T0dwVzJxWkJPSm00ClNqTCtlYkxPSFRuMlBodU1zVmc5
            YXA2M00rc0NtdkRIVU9WcmFGQTZKMVUKLS0tIG5ocEsyUlJXTDlFVmppUi80RnE3
            bFVtMyt5djBiNHRwVVk2L1F5Qzdka0EKYq9+7g1B7ieSsQTFbCLJ6ChGnYvUCikD
            tErb05YqihEpvNsoqvN9kAidCyIR9nFroORijz6hoBaY8FyVQCJ0eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T20:32:22Z"
    mac: ENC[AES256_GCM,data:GbntewVmQu3k2RcX9EuKNXV/1z7d6QoDb+GLpGoX0NYbUfcsQp+ba9zf+vc3xyJ72vmEdGeRWhcKuxsF8uWCxBT5aN1AmrI19X1figDkN9FMyDjc27OQ5sf+6oys5TZ7JPEKH29XBgP+RCCc60NlG9YqNVZs6dNdb9ksUlZCvjA=,iv:lXsmFyecMMNEKfuXglJxW4mjK5XaYYox6G4PpnYNqu0=,tag:tSzFUBmSn3apbxtstjIwOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
