apiVersion: ENC[AES256_GCM,data:Ykc=,iv:FM7A1BbkL+911CBp8FOIXHs5SswAdWbfuyCy6gUglO4=,tag:WZREqV+Uv00t7/JAqAqtKA==,type:str]
data:
    cloud: ENC[AES256_GCM,data:45dM+9istT6Qe6gxHgtozpXOU2KrmE26E1dX2PMuubeHorKVzKKlzbVzKTUbJ3Q8Jk65OfpLaskQepox0MVJrTgFUVHJaLs5DnWPdGYRIHC2fr1tZhJpI8PMFGSx6A3T3+fBPMxdQ8pe71DveEMJGQpGZ7obD/aWN+PAFYlnfJRGgQAdBV5SYorGCgKNrkOpdIz0loscWB0sMF5y3WmooQwjaBnRiHpbCqwRz6MpO/LOw+iEgWrgSYp55SSy1AVv7d2kEsOg5yH6EimT,iv:JT1kv9pLxE+Q1FICKT5UVF8pksR75WS8rCC7DUJ9lxs=,tag:X0HPbKHuQFIe168wjoaCZA==,type:str]
kind: ENC[AES256_GCM,data:StOcIOKx,iv:m6VqvHCDCg578fTvSTb/YQaqsK6O4kUawpvHo2XAz+I=,tag:ZJt4bodNNzT5/Pz33R9rMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZZvGmWxkge3XCPuOBmAXvqJ0sSpm,iv:T0Kly86LETSFlRtNWdOoaWDOq2iRP87VWOTxwk56GpI=,tag:P7x5Y5vo68er8cKj42szpg==,type:str]
    namespace: ENC[AES256_GCM,data:+45N1q69,iv:i/GVJBFyU0IC4oDAEXDdP7Zf5+yYW9CLNTCvgM5hE5w=,tag:PKVdLsOMl3p6C9BjTaYEZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z08eccrjwzvvgllv2n3553v6ajs4ucvcv26wjcnqtqvkuhu8hsfsrg5pzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUHNkeFNaZit4MlhDbWRZ
            QkdGc1lRS0VTMm9BMTViVDZvWnJSU0F6eFdvCnE1VVVIKys4ZXF6aVhoRHNhOS8v
            cmVoaU1EU0FLVEY5RWZyL2hLWWZQWEEKLS0tIHVkZ2piMHF5VHFEUHRUUUJybk9V
            Q0FCNmg2Ylp1MjJKcEFHVWVxT3ZSR00KA3e8eL7yUxfldbtinxtXFeT6ljwYwnuz
            V4Y4/P0MBLn4VQyEgitxgI0L+7yoSqBBU6ZpjulW160/r+qjWMfQgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T20:52:01Z"
    mac: ENC[AES256_GCM,data:GRzXWjsutpTgtm4URJydtAwvEfry8Oy9IZFa9O6u5avmunpYBxLMBqjLIK1maXyDTnA2mA0nSkTYnDCpxcWiQN9MXmEEbSZTx2WcPZ2sR9yi8G7RUlh3n0pO8/YbsXgdp5Uss5Zb6DrZCGxDz+ta2YS/Cn79Y/uihvk418pv5GM=,iv:QgQ3QbWTgGPaM+Z9Xy+qFx48RV3k7EkDWPj3OjS+n+k=,tag:zRzcPr9fGE28XZ1ePTr2oA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
